/**
 * ReportPreview
 *
 * Renders a DoctorReportData object as a beautiful on-screen preview.
 *
 * ─── COMPOSITION ────────────────────────────────────────────────────
 *
 *  1. Header — title + range label + generation timestamp
 *  2. Cycle Summary section
 *  3. Most Frequent Symptoms section
 *  4. Wellbeing Trends section
 *  5. Most Recent Cycles section
 *  6. Medications section (stub for v1)
 *  7. Footer — warm medical disclaimer
 *
 *  When DoctorReportData.isSparse is true we swap in an encouraging
 *  empty state instead of showing a wall of "0"s and "—"s.
 */

import { View, Text, StyleSheet, ScrollView } from 'react-native';
import { Colors } from '../../constants/colors';
import { Typography } from '../../constants/typography';
import { Spacing } from '../../constants/spacing';
import {
  DoctorReportData,
  ReportSymptomEntry,
} from '../../types/report.types';
import { ReportSection } from './ReportSection';

interface ReportPreviewProps {
  data: DoctorReportData;
}

export function ReportPreview({ data }: ReportPreviewProps) {
  if (data.isSparse) {
    return <SparsePreview data={data} />;
  }

  return (
    <ScrollView
      style={styles.scroll}
      contentContainerStyle={styles.scrollContent}
      showsVerticalScrollIndicator={false}
    >
      {/* Header */}
      <View style={styles.header}>
        <Text style={styles.headerTitle}>Your Health Summary</Text>
        <Text style={styles.headerMeta}>
          {data.range.label} · Generated {formatTimestamp(data.generatedAt)}
        </Text>
      </View>

      {/* Cycle Summary */}
      <ReportSection
        emoji="🌙"
        title="Cycle Summary"
        subtitle={`${data.cycleSummary.cyclesTracked} ${data.cycleSummary.cyclesTracked === 1 ? 'complete cycle' : 'complete cycles'}`}
      >
        <CycleSummaryBody data={data} />
      </ReportSection>

      {/* Symptoms */}
      <ReportSection
        emoji="🌿"
        title="Most Frequent Symptoms"
        subtitle={
          data.symptoms.totalLogged === 0
            ? 'No symptoms logged in this range'
            : `${data.symptoms.totalLogged} total ${data.symptoms.totalLogged === 1 ? 'log' : 'logs'}`
        }
      >
        <SymptomsBody data={data} />
      </ReportSection>

      {/* Wellbeing */}
      <ReportSection
        emoji="💛"
        title="Wellbeing Trends"
        subtitle={`${data.wellbeing.daysWithCheckIn} of ${data.wellbeing.totalDaysInRange} days checked in`}
      >
        <WellbeingBody data={data} />
      </ReportSection>

      {/* Recent Cycles */}
      <ReportSection
        emoji="📅"
        title="Most Recent Cycles"
      >
        <RecentCyclesBody data={data} />
      </ReportSection>

      {/* Medications (stub) */}
      <ReportSection emoji="💊" title="Medications">
        <Text style={styles.bodyText}>{data.medications.note}</Text>
      </ReportSection>

      {/* Footer */}
      <View style={styles.footer}>
        <Text style={styles.footerTitle}>A gentle note for your clinician</Text>
        <Text style={styles.footerText}>
          This is a summary of self-reported data from Dottie. It is not a
          medical diagnosis. Please consider it alongside your own clinical
          judgment. 💛
        </Text>
        <Text style={styles.footerMeta}>
          Generated by Dottie v{data.appVersion}
        </Text>
      </View>
    </ScrollView>
  );
}

// ─── SECTION BODIES ──────────────────────────────────────────────────

function CycleSummaryBody({ data }: { data: DoctorReportData }) {
  const cs = data.cycleSummary;
  if (cs.cyclesTracked === 0) {
    return <Text style={styles.bodyText}>{cs.regularityNote}</Text>;
  }

  return (
    <View style={styles.kvList}>
      {cs.averageCycleLength !== null && (
        <KeyValue
          label="Average cycle length"
          value={
            cs.cycleLengthRange
              ? `${cs.averageCycleLength} days  (range ${cs.cycleLengthRange[0]}–${cs.cycleLengthRange[1]})`
              : `${cs.averageCycleLength} days`
          }
        />
      )}
      {cs.averagePeriodLength !== null && (
        <KeyValue
          label="Average period length"
          value={
            cs.periodLengthRange
              ? `${cs.averagePeriodLength} days  (range ${cs.periodLengthRange[0]}–${cs.periodLengthRange[1]})`
              : `${cs.averagePeriodLength} days`
          }
        />
      )}
      <KeyValue label="Regularity" value={regularityDisplay(cs.regularity)} />
      <Text style={[styles.bodyText, styles.regularityNote]}>{cs.regularityNote}</Text>
    </View>
  );
}

function SymptomsBody({ data }: { data: DoctorReportData }) {
  if (data.symptoms.entries.length === 0) {
    return (
      <Text style={styles.bodyText}>
        Nothing logged in this range yet. Logging symptoms — even small ones —
        builds the pattern your doctor will find most useful. 🌱
      </Text>
    );
  }

  return (
    <View style={styles.symptomsList}>
      {data.symptoms.entries.map((entry) => (
        <SymptomRow key={entry.symptomType} entry={entry} />
      ))}
    </View>
  );
}

function WellbeingBody({ data }: { data: DoctorReportData }) {
  const w = data.wellbeing;
  return (
    <View style={styles.kvList}>
      <KeyValue label="Mood" value={formatAvg(w.averageMood)} />
      <KeyValue label="Energy" value={formatAvg(w.averageEnergy)} />
      <KeyValue label="Sleep" value={formatAvg(w.averageSleep)} />
      <KeyValue label="Stress" value={formatAvg(w.averageStress)} />
    </View>
  );
}

function RecentCyclesBody({ data }: { data: DoctorReportData }) {
  if (data.recentCycles.rows.length === 0) {
    return (
      <Text style={styles.bodyText}>
        No complete cycles in this range. Your next period start will add the
        first entry here.
      </Text>
    );
  }

  return (
    <View style={styles.cyclesList}>
      {data.recentCycles.rows.map((row, idx) => (
        <View key={`${row.startDate}-${idx}`} style={styles.cycleRow}>
          <Text style={styles.cycleDates}>
            {formatShortDate(row.startDate)} → {formatShortDate(row.endDate)}
          </Text>
          <Text style={styles.cycleMeta}>
            {row.cycleLength} day cycle · {row.periodLength} day period
          </Text>
        </View>
      ))}
      {data.recentCycles.hasMore && (
        <Text style={[styles.bodyText, styles.moreNote]}>
          … and earlier cycles in your history
        </Text>
      )}
    </View>
  );
}

// ─── SUBCOMPONENTS ───────────────────────────────────────────────────

function KeyValue({ label, value }: { label: string; value: string }) {
  return (
    <View style={styles.kvRow}>
      <Text style={styles.kvLabel}>{label}</Text>
      <Text style={styles.kvValue}>{value}</Text>
    </View>
  );
}

function SymptomRow({ entry }: { entry: ReportSymptomEntry }) {
  return (
    <View style={styles.symptomRow}>
      <View style={styles.symptomMain}>
        <Text style={styles.symptomName}>{prettifySymptom(entry.symptomType)}</Text>
        <Text style={styles.symptomMeta}>
          {entry.occurrences}× · avg {entry.averageSeverity}/10
          {entry.mostCommonPhase
            ? ` · usually in ${prettifyPhase(entry.mostCommonPhase)}`
            : ''}
        </Text>
      </View>
    </View>
  );
}

// ─── SPARSE STATE ────────────────────────────────────────────────────

function SparsePreview({ data }: { data: DoctorReportData }) {
  return (
    <View style={styles.sparseContainer}>
      <Text style={styles.sparseEmoji}>🌱</Text>
      <Text style={styles.sparseTitle}>Your story is just beginning</Text>
      <Text style={styles.sparseBody}>
        Doctor reports become powerful with a few weeks of logging.
        Keep checking in daily, log your symptoms when they show up, and
        we'll have a beautiful summary ready for you very soon.
      </Text>
      <Text style={styles.sparseMeta}>
        Range checked: {data.range.label}
      </Text>
    </View>
  );
}

// ─── HELPERS ─────────────────────────────────────────────────────────

function formatAvg(n: number | null): string {
  return n === null ? '— not logged yet' : `${n.toFixed(1)} / 5`;
}

function regularityDisplay(r: DoctorReportData['cycleSummary']['regularity']): string {
  switch (r) {
    case 'regular':         return 'Regular ✨';
    case 'mostly_regular':  return 'Mostly regular 🌱';
    case 'irregular':       return 'Variable';
    case 'insufficient_data': return 'Still learning';
  }
}

function prettifySymptom(raw: string): string {
  return raw.charAt(0).toUpperCase() + raw.slice(1).replace(/_/g, ' ');
}

function prettifyPhase(phase: string): string {
  return phase.charAt(0).toUpperCase() + phase.slice(1);
}

function formatShortDate(iso: string): string {
  const d = new Date(`${iso}T00:00:00`);
  return d.toLocaleDateString(undefined, { month: 'short', day: 'numeric' });
}

function formatTimestamp(iso: string): string {
  const d = new Date(iso);
  return d.toLocaleDateString(undefined, {
    month: 'short', day: 'numeric', year: 'numeric',
  });
}

// ─── STYLES ──────────────────────────────────────────────────────────

const styles = StyleSheet.create({
  scroll: {
    flex: 1,
    backgroundColor: Colors.surface.background,
  },
  scrollContent: {
    padding: Spacing.screenPadding,
    paddingBottom: Spacing['4xl'],
  },
  header: {
    marginBottom: Spacing.sectionGap,
  },
  headerTitle: {
    ...Typography.preset.h2,
    color: Colors.text.primary,
    marginBottom: 4,
  },
  headerMeta: {
    ...Typography.preset.caption,
    color: Colors.text.tertiary,
  },

  // Body text shared across sections
  bodyText: {
    ...Typography.preset.body,
    color: Colors.text.secondary,
  },
  regularityNote: {
    marginTop: Spacing.xs,
    fontStyle: 'italic',
  },

  // Key-value rows
  kvList: {
    gap: Spacing.sm,
  },
  kvRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    paddingVertical: 4,
  },
  kvLabel: {
    ...Typography.preset.caption,
    color: Colors.text.tertiary,
    flexShrink: 1,
    marginRight: Spacing.md,
  },
  kvValue: {
    ...Typography.preset.bodySemibold,
    color: Colors.text.primary,
    flexShrink: 0,
    textAlign: 'right',
  },

  // Symptoms list
  symptomsList: {
    gap: Spacing.sm,
  },
  symptomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: Spacing.xs,
  },
  symptomMain: {
    flex: 1,
  },
  symptomName: {
    ...Typography.preset.bodySemibold,
    color: Colors.text.primary,
  },
  symptomMeta: {
    ...Typography.preset.caption,
    color: Colors.text.tertiary,
    marginTop: 2,
  },

  // Recent cycles
  cyclesList: {
    gap: Spacing.sm,
  },
  cycleRow: {
    paddingVertical: Spacing.xs,
  },
  cycleDates: {
    ...Typography.preset.bodySemibold,
    color: Colors.text.primary,
  },
  cycleMeta: {
    ...Typography.preset.caption,
    color: Colors.text.tertiary,
    marginTop: 2,
  },
  moreNote: {
    fontStyle: 'italic',
    marginTop: Spacing.xs,
  },

  // Footer
  footer: {
    marginTop: Spacing.md,
    padding: Spacing.cardPaddingLarge,
    borderRadius: Spacing.radius.xl,
    backgroundColor: Colors.surface.cardElevated,
  },
  footerTitle: {
    ...Typography.preset.bodySemibold,
    color: Colors.text.primary,
    marginBottom: Spacing.xs,
  },
  footerText: {
    ...Typography.preset.body,
    color: Colors.text.secondary,
    marginBottom: Spacing.sm,
  },
  footerMeta: {
    ...Typography.preset.caption,
    color: Colors.text.tertiary,
  },

  // Sparse state
  sparseContainer: {
    flex: 1,
    padding: Spacing.screenPadding,
    paddingTop: Spacing['4xl'],
    alignItems: 'center',
  },
  sparseEmoji: {
    fontSize: 56,
    marginBottom: Spacing.lg,
  },
  sparseTitle: {
    ...Typography.preset.h3,
    color: Colors.text.primary,
    marginBottom: Spacing.sm,
    textAlign: 'center',
  },
  sparseBody: {
    ...Typography.preset.body,
    color: Colors.text.secondary,
    textAlign: 'center',
    marginBottom: Spacing.lg,
    paddingHorizontal: Spacing.md,
  },
  sparseMeta: {
    ...Typography.preset.caption,
    color: Colors.text.tertiary,
  },
});
