/**
 * Dottie — Seed Question Bank
 *
 * The phase-responsive questions shown on the home screen each day.
 * 80 questions covering all 4 phases × 4 day-bands × 5 questions, each
 * with companion voice variants for all 6 spirit companions.
 *
 * Shape: one PhaseQuestion[] per cohort state — wired into the
 * ContentResolver via SeededCohortProvider in the app's bootstrap.
 *
 * Coverage:
 *   menstrual:   1-3, 4-7, 8-11, 12-14  (5 questions each = 20 total)
 *   follicular:  1-3, 4-7, 8-11, 12-14  (5 questions each = 20 total)
 *   ovulatory:   1-3, 4-7, 8-11, 12-14  (5 questions each = 20 total)
 *   luteal:      1-3, 4-7, 8-11, 12-14  (5 questions each = 20 total)
 *
 * All questions target mode='adult' + cluster='none'. The graceful
 * degradation chain in the engine layers (ContentResolver fallbacks)
 * uses these as the baseline that all other cohorts fall back to.
 *
 * Adding more cohort variants? Append new entries with different
 * mode/cluster combinations — they'll be picked up automatically.
 */

import { PhaseQuestion } from '../types/content.types';

// ─── MENSTRUAL PHASE ─────────────────────────────────────────────────

const MENSTRUAL_D1_3: PhaseQuestion[] = [
  {
    id: 'q_menstrual_d1-3_1',
    phase: 'menstrual',
    mode: 'adult',
    text: 'How are your cramps today?',
    type: 'scale',
    options: ['None', 'Mild', 'Moderate', 'Strong', 'Intense'],
    tracksMetric: 'cramps',
    companionVariants: {
      fox: 'Luna asks gently: how are the cramps today? 🦊',
      bunny: "Pip wants to know — cramps level? Be honest! 🐰",
      butterfly: 'Mira asks: where does your body need softness today? ✨',
      cat: 'Nyx demands a cramp report. No lying 😼',
      owl: 'Sage asks: scale the cramps so we can pattern them 🦉',
      blossom: 'How are the cramps today, friend? 🩷',
    },
  },
  {
    id: 'q_menstrual_d1-3_2',
    phase: 'menstrual',
    mode: 'adult',
    text: 'How is your energy level today?',
    type: 'scale',
    options: ['Drained', 'Low', 'Okay', 'Good', 'Great'],
    tracksMetric: 'energy',
    companionVariants: {
      fox: 'Luna wonders about your energy today 🦊',
      bunny: 'Pip wants the energy update! 🐰',
      butterfly: 'Mira asks: where does your spark sit today? ✨',
      cat: 'Nyx needs to know if you can match her napping pace 😼',
      owl: 'Sage notes: rate your energy honestly for the data 🦉',
      blossom: 'How is your energy, sweet one? 🩷',
    },
  },
  {
    id: 'q_menstrual_d1-3_3',
    phase: 'menstrual',
    mode: 'adult',
    text: 'How are you feeling emotionally?',
    type: 'emoji',
    options: ['😢', '😕', '😐', '🙂', '😊'],
    tracksMetric: 'mood',
    companionVariants: {
      fox: 'Luna sees your heart. How does it feel? 🦊',
      bunny: 'Pip wants the FEELS check-in! 🐰',
      butterfly: 'Mira asks: which emotion is loudest right now? ✨',
      cat: 'Nyx tolerates emotions. Tell her yours 😼',
      owl: 'Sage logs mood. What rating fits today? 🦉',
      blossom: 'How are you feeling? 🩷',
    },
  },
  {
    id: 'q_menstrual_d1-3_4',
    phase: 'menstrual',
    mode: 'adult',
    text: 'Did you sleep okay last night?',
    type: 'scale',
    options: ['Restless', 'Poor', 'Okay', 'Good', 'Deep'],
    tracksMetric: 'sleep',
    companionVariants: {
      fox: 'Luna asks: how was the rest? 🦊',
      bunny: 'Pip wants the sleep report! 🐰💤',
      butterfly: 'Mira asks: did dreams visit you well? ✨',
      cat: 'Nyx slept 14 hours. Did you sleep AT ALL? 😼',
      owl: 'Sage logs sleep quality. Rate it 🦉',
      blossom: 'How did you sleep? 🩷',
    },
  },
  {
    id: 'q_menstrual_d1-3_5',
    phase: 'menstrual',
    mode: 'adult',
    text: 'How heavy is your flow today?',
    type: 'scale',
    options: ['None', 'Spotting', 'Light', 'Medium', 'Heavy'],
    tracksMetric: 'flow',
    companionVariants: {
      fox: 'Luna keeps track of the rhythm 🦊',
      bunny: 'Pip needs the flow update! 🐰',
      butterfly: 'Mira observes the body without judgment ✨',
      cat: 'Nyx wants efficient data. Quick log 😼',
      owl: 'Sage logs flow. Pick a level 🦉',
      blossom: 'How is the flow today? 🩷',
    },
  },
];

const MENSTRUAL_D4_7: PhaseQuestion[] = [
  {
    id: 'q_menstrual_d4-7_1',
    phase: 'menstrual',
    mode: 'adult',
    text: 'Is your energy starting to come back?',
    type: 'scale',
    options: ['Not yet', 'A little', 'Definitely', 'Almost normal', 'Fully back'],
    tracksMetric: 'energy',
    companionVariants: {
      fox: 'Luna wonders if the lift is starting yet 🦊',
      bunny: 'Pip is checking — feeling the BOUNCE-BACK?! 🐰',
      butterfly: 'Mira asks: is the season shifting in you? ✨',
      cat: 'Nyx wants to know if you can leave the bed yet 😼',
      owl: 'Sage notes: estrogen rises — rate the rebound 🦉',
      blossom: 'Energy returning yet? 🩷',
    },
  },
  {
    id: 'q_menstrual_d4-7_2',
    phase: 'menstrual',
    mode: 'adult',
    text: 'How is your mood today?',
    type: 'emoji',
    options: ['😢', '😕', '😐', '🙂', '😊'],
    tracksMetric: 'mood',
    companionVariants: {
      fox: 'Luna checks in on your inner weather 🦊',
      bunny: 'Pip wants the mood update! 🐰',
      butterfly: 'Mira asks: which emoji is your heart today? ✨',
      cat: 'Nyx categorizes feelings ruthlessly. Pick one 😼',
      owl: 'Sage logs your mood. Honest emoji please 🦉',
      blossom: 'How are you feeling today? 🩷',
    },
  },
  {
    id: 'q_menstrual_d4-7_3',
    phase: 'menstrual',
    mode: 'adult',
    text: 'Did you drink enough water yesterday?',
    type: 'boolean',
    options: ['Not really', 'Yes I did'],
    tracksMetric: 'hydration',
    companionVariants: {
      fox: 'Luna sips and asks: did you hydrate? 🦊',
      bunny: 'Pip is the HYDRATION POLICE! Yes or no?! 🐰',
      butterfly: 'Mira asks: did water visit you enough? ✨',
      cat: 'Nyx requires you to refill your bowl. I mean, glass 😼',
      owl: 'Sage logs hydration honestly. No fudging 🦉',
      blossom: 'Did you drink enough water? 🩷',
    },
  },
  {
    id: 'q_menstrual_d4-7_4',
    phase: 'menstrual',
    mode: 'adult',
    text: 'Any cravings showing up today?',
    type: 'choice',
    options: ['None', 'Sweet', 'Salty', 'Carbs', 'Chocolate'],
    tracksMetric: 'cravings',
    companionVariants: {
      fox: 'Luna asks: what is your body asking for? 🦊',
      bunny: 'Pip is CURIOUS about cravings today! 🐰',
      butterfly: 'Mira asks: what flavors call to you? ✨',
      cat: 'Nyx supports all cravings. Tell her which 😼',
      owl: 'Sage logs cravings. Pick the strongest 🦉',
      blossom: 'Any cravings? 🩷 Listen to them',
    },
  },
  {
    id: 'q_menstrual_d4-7_5',
    phase: 'menstrual',
    mode: 'adult',
    text: 'How is your skin today?',
    type: 'choice',
    options: ['Breakout', 'Oily', 'Normal', 'Clear', 'Glowing'],
    tracksMetric: 'skin',
    companionVariants: {
      fox: 'Luna observes the small changes in your skin 🦊',
      bunny: 'Pip is doing the SKIN CHECK! 🐰',
      butterfly: 'Mira sees the subtle shifts in your glow ✨',
      cat: 'Nyx grooms in solidarity. Skin status? 😼',
      owl: 'Sage logs skin condition. Pick the closest 🦉',
      blossom: 'How is your skin? 🩷',
    },
  },
];

const MENSTRUAL_D8_11: PhaseQuestion[] = [
  {
    id: 'q_menstrual_d8-11_1',
    phase: 'menstrual',
    mode: 'adult',
    text: 'Is your period still going?',
    type: 'boolean',
    options: ['Still bleeding', 'It ended'],
    tracksMetric: 'flow',
    companionVariants: {
      fox: 'Luna asks gently: is the flow still here? 🦊',
      bunny: 'Pip needs the period update! Still here?! 🐰',
      butterfly: 'Mira observes the body honestly ✨',
      cat: 'Nyx requires factual updates 😼',
      owl: 'Sage logs flow status. Yes or no 🦉',
      blossom: 'Is your period still going? 🩷',
    },
  },
  {
    id: 'q_menstrual_d8-11_2',
    phase: 'menstrual',
    mode: 'adult',
    text: 'How is your energy holding up?',
    type: 'scale',
    options: ['Drained', 'Low', 'Okay', 'Good', 'Great'],
    tracksMetric: 'energy',
    companionVariants: {
      fox: 'Luna checks the energy meter 🦊',
      bunny: 'Pip is checking your VIBE 🐰',
      butterfly: 'Mira asks: where is your spark holding? ✨',
      cat: 'Nyx requires regular energy updates 😼',
      owl: 'Sage logs energy. Rate it 🦉',
      blossom: 'How is your energy? 🩷',
    },
  },
  {
    id: 'q_menstrual_d8-11_3',
    phase: 'menstrual',
    mode: 'adult',
    text: 'How are you feeling overall?',
    type: 'emoji',
    options: ['😢', '😕', '😐', '🙂', '😊'],
    tracksMetric: 'mood',
    companionVariants: {
      fox: 'Luna takes your emotional pulse 🦊',
      bunny: 'Pip wants the FEELS! 🐰',
      butterfly: 'Mira asks: which mood is yours today? ✨',
      cat: 'Nyx assesses your mood. Pick wisely 😼',
      owl: 'Sage logs mood for the pattern 🦉',
      blossom: 'How are you feeling overall? 🩷',
    },
  },
  {
    id: 'q_menstrual_d8-11_4',
    phase: 'menstrual',
    mode: 'adult',
    text: 'Did you move your body today?',
    type: 'boolean',
    options: ['Not yet', 'Yes'],
    tracksMetric: 'exercise',
    companionVariants: {
      fox: 'Luna asks: any gentle movement today? 🦊',
      bunny: 'Pip is the MOVEMENT BUNNY! Did you move?! 🐰',
      butterfly: 'Mira asks: did your body get to dance today? ✨',
      cat: 'Nyx considers walking to the kitchen exercise 😼',
      owl: 'Sage logs activity. Even small counts 🦉',
      blossom: 'Did you move at all today? 🩷',
    },
  },
  {
    id: 'q_menstrual_d8-11_5',
    phase: 'menstrual',
    mode: 'adult',
    text: 'Any lingering cramps or pain?',
    type: 'scale',
    options: ['None', 'Mild', 'Moderate', 'Strong', 'Severe'],
    tracksMetric: 'cramps',
    companionVariants: {
      fox: 'Luna asks honestly about lingering pain 🦊',
      bunny: 'Pip is checking for LEFTOVER cramps! 🐰',
      butterfly: 'Mira asks: where does your body still ache? ✨',
      cat: 'Nyx demands a pain report. Now 😼',
      owl: 'Sage logs lingering pain — pattern matters 🦉',
      blossom: 'Any pain still hanging around? 🩷',
    },
  },
];

const MENSTRUAL_D12_14: PhaseQuestion[] = [
  {
    id: 'q_menstrual_d12-14_1',
    phase: 'menstrual',
    mode: 'adult',
    text: 'Is your cycle longer than usual this month?',
    type: 'boolean',
    options: ['About the same', 'Longer than normal'],
    tracksMetric: 'cycle_length',
    companionVariants: {
      fox: 'Luna observes patterns over time 🦊',
      bunny: 'Pip wants to compare to your usual! 🐰',
      butterfly: 'Mira watches the long arc of your cycles ✨',
      cat: 'Nyx requires comparative data 😼',
      owl: 'Sage logs cycle length deviation 🦉',
      blossom: 'Longer than usual this time? 🩷',
    },
  },
  {
    id: 'q_menstrual_d12-14_2',
    phase: 'menstrual',
    mode: 'adult',
    text: 'How is your stress level today?',
    type: 'scale',
    options: ['Calm', 'Low', 'Okay', 'High', 'Overwhelmed'],
    tracksMetric: 'stress',
    companionVariants: {
      fox: 'Luna asks about the inner storm 🦊',
      bunny: 'Pip wants the STRESS-O-METER reading! 🐰',
      butterfly: 'Mira asks: how loud is the world today? ✨',
      cat: 'Nyx judges stress levels. Pick yours 😼',
      owl: 'Sage notes: stress shifts cycle length — log it 🦉',
      blossom: 'How stressed are you today? 🩷',
    },
  },
  {
    id: 'q_menstrual_d12-14_3',
    phase: 'menstrual',
    mode: 'adult',
    text: 'Did you sleep well last night?',
    type: 'scale',
    options: ['Awful', 'Poor', 'Okay', 'Good', 'Amazing'],
    tracksMetric: 'sleep',
    companionVariants: {
      fox: 'Luna asks: was rest kind to you? 🦊',
      bunny: 'Pip wants the sleep report! 🐰💤',
      butterfly: 'Mira asks: did the night hold you well? ✨',
      cat: 'Nyx slept fabulously. You? 😼',
      owl: 'Sage logs sleep quality 🦉',
      blossom: 'How was your sleep? 🩷',
    },
  },
  {
    id: 'q_menstrual_d12-14_4',
    phase: 'menstrual',
    mode: 'adult',
    text: 'How is your appetite today?',
    type: 'choice',
    options: ['Low', 'Normal', 'High', 'Very high'],
    tracksMetric: 'appetite',
    companionVariants: {
      fox: 'Luna asks: how hungry today? 🦊',
      bunny: 'Pip is doing the SNACK CHECK! 🐰',
      butterfly: 'Mira asks: what does your body need to eat? ✨',
      cat: 'Nyx supports all appetite levels 😼',
      owl: 'Sage logs appetite — useful for cycle pattern 🦉',
      blossom: 'How is your appetite? 🩷',
    },
  },
  {
    id: 'q_menstrual_d12-14_5',
    phase: 'menstrual',
    mode: 'adult',
    text: 'Are you feeling like yourself again?',
    type: 'emoji',
    options: ['😟', '😕', '😐', '🙂', '😊'],
    tracksMetric: 'mood',
    companionVariants: {
      fox: 'Luna asks: are you returning to yourself? 🦊',
      bunny: 'Pip wants to know if you feel like YOU! 🐰',
      butterfly: 'Mira asks: have you found your center again? ✨',
      cat: 'Nyx requires confirmation of normality 😼',
      owl: 'Sage logs your post-menstrual baseline 🦉',
      blossom: 'Feeling more like yourself? 🩷',
    },
  },
];

// ─── FOLLICULAR PHASE ────────────────────────────────────────────────

const FOLLICULAR_D1_3: PhaseQuestion[] = [
  {
    id: 'q_follicular_d1-3_1',
    phase: 'follicular',
    mode: 'adult',
    text: 'Feeling the energy lift?',
    type: 'scale',
    options: ['Not yet', 'A little', 'Yes', 'Definitely', 'Big time'],
    tracksMetric: 'energy',
    companionVariants: {
      fox: 'Luna feels the spring in your step 🦊',
      bunny: 'Pip is BOUNCING — are you?! 🐰',
      butterfly: 'Mira watches the bloom begin ✨',
      cat: 'Nyx senses your sudden ambition 😼',
      owl: 'Sage notes: estrogen climbs — rate the lift 🦉',
      blossom: 'Feel that lift? 🩷',
    },
  },
  {
    id: 'q_follicular_d1-3_2',
    phase: 'follicular',
    mode: 'adult',
    text: 'How is your mood today?',
    type: 'emoji',
    options: ['😢', '😕', '😐', '🙂', '😊'],
    tracksMetric: 'mood',
    companionVariants: {
      fox: 'Luna asks about your inner weather 🦊',
      bunny: 'Pip wants the FEELS check-in! 🐰',
      butterfly: 'Mira asks: which mood is yours today? ✨',
      cat: 'Nyx categorizes feelings. Pick one 😼',
      owl: 'Sage logs mood. Honest emoji 🦉',
      blossom: 'How are you feeling today? 🩷',
    },
  },
  {
    id: 'q_follicular_d1-3_3',
    phase: 'follicular',
    mode: 'adult',
    text: 'Sleep quality last night?',
    type: 'scale',
    options: ['Restless', 'Poor', 'Okay', 'Good', 'Deep'],
    tracksMetric: 'sleep',
    companionVariants: {
      fox: 'Luna asks: was sleep kind to you? 🦊',
      bunny: 'Pip wants the SLEEP report! 🐰💤',
      butterfly: 'Mira asks: did the night carry you well? ✨',
      cat: 'Nyx slept perfectly. You? 😼',
      owl: 'Sage logs sleep quality 🦉',
      blossom: 'How was sleep last night? 🩷',
    },
  },
  {
    id: 'q_follicular_d1-3_4',
    phase: 'follicular',
    mode: 'adult',
    text: 'How is your skin looking today?',
    type: 'choice',
    options: ['Breakout', 'Oily', 'Normal', 'Clear', 'Glowing'],
    tracksMetric: 'skin',
    companionVariants: {
      fox: 'Luna sees the glow returning 🦊',
      bunny: 'Pip is doing the GLOW check! 🐰✨',
      butterfly: 'Mira watches you light up from within ✨',
      cat: 'Nyx grooms in solidarity. Skin status? 😼',
      owl: 'Sage notes: estrogen boosts skin — log it 🦉',
      blossom: 'How is your skin today? 🩷',
    },
  },
  {
    id: 'q_follicular_d1-3_5',
    phase: 'follicular',
    mode: 'adult',
    text: 'Are you feeling motivated?',
    type: 'boolean',
    options: ['Not really', 'Yes!'],
    tracksMetric: 'motivation',
    companionVariants: {
      fox: 'Luna asks: is the spark there today? 🦊',
      bunny: 'Pip wants to know — MOTIVATED?! 🐰',
      butterfly: 'Mira asks: does your spirit want to move? ✨',
      cat: 'Nyx is rarely motivated. You? 😼',
      owl: 'Sage logs motivation — pattern matters 🦉',
      blossom: 'Feeling motivated? 🩷',
    },
  },
];

const FOLLICULAR_D4_7: PhaseQuestion[] = [
  {
    id: 'q_follicular_d4-7_1',
    phase: 'follicular',
    mode: 'adult',
    text: 'How is your focus today?',
    type: 'scale',
    options: ['Scattered', 'Foggy', 'Okay', 'Sharp', 'Laser'],
    tracksMetric: 'focus',
    companionVariants: {
      fox: 'Luna sees clarity in your eyes today 🦊',
      bunny: 'Pip wants the BRAIN report! Sharp?! 🐰',
      butterfly: 'Mira asks: where is your mind landing today? ✨',
      cat: 'Nyx is laser-focused on naps. You? 😼',
      owl: 'Sage notes: estrogen + cognition — rate focus 🦉',
      blossom: 'How is your focus? 🩷',
    },
  },
  {
    id: 'q_follicular_d4-7_2',
    phase: 'follicular',
    mode: 'adult',
    text: 'Energy level today?',
    type: 'scale',
    options: ['Low', 'Steady', 'Lifted', 'High', 'Electric'],
    tracksMetric: 'energy',
    companionVariants: {
      fox: 'Luna feels your energy is rising 🦊',
      bunny: 'Pip is checking — ELECTRIC?! 🐰⚡',
      butterfly: 'Mira watches your spark grow brighter ✨',
      cat: 'Nyx is impressed. Briefly 😼',
      owl: 'Sage logs energy level 🦉',
      blossom: 'How is your energy? 🩷',
    },
  },
  {
    id: 'q_follicular_d4-7_3',
    phase: 'follicular',
    mode: 'adult',
    text: 'Did you exercise or move today?',
    type: 'boolean',
    options: ['Not yet', 'Yes!'],
    tracksMetric: 'exercise',
    companionVariants: {
      fox: 'Luna asks about movement today 🦊',
      bunny: 'Pip is the WORKOUT BUDDY! Did you move?! 🐰',
      butterfly: 'Mira asks: did your body get to celebrate? ✨',
      cat: 'Nyx prefers stillness. You? 😼',
      owl: 'Sage logs exercise. Even small counts 🦉',
      blossom: 'Did you move today? 🩷',
    },
  },
  {
    id: 'q_follicular_d4-7_4',
    phase: 'follicular',
    mode: 'adult',
    text: 'How are you feeling socially?',
    type: 'scale',
    options: ['Hermit', 'Quiet', 'Open', 'Social', 'Magnetic'],
    tracksMetric: 'social_energy',
    companionVariants: {
      fox: 'Luna asks: who do you want to see today? 🦊',
      bunny: 'Pip is SOCIAL BUNNY! Are you?! 🐰',
      butterfly: 'Mira asks: where do you want to land socially? ✨',
      cat: 'Nyx prefers solitude. Always 😼',
      owl: 'Sage logs social energy — useful pattern 🦉',
      blossom: 'How is your social energy? 🩷',
    },
  },
  {
    id: 'q_follicular_d4-7_5',
    phase: 'follicular',
    mode: 'adult',
    text: 'Any cravings today?',
    type: 'choice',
    options: ['None', 'Sweet', 'Salty', 'Protein', 'Veggies'],
    tracksMetric: 'cravings',
    companionVariants: {
      fox: 'Luna asks what your body wants 🦊',
      bunny: 'Pip is doing the CRAVING check! 🐰',
      butterfly: 'Mira asks: which flavors call you? ✨',
      cat: 'Nyx supports all cravings 😼',
      owl: 'Sage logs cravings — pattern matters 🦉',
      blossom: 'Any cravings today? 🩷',
    },
  },
];

const FOLLICULAR_D8_11: PhaseQuestion[] = [
  {
    id: 'q_follicular_d8-11_1',
    phase: 'follicular',
    mode: 'adult',
    text: 'Feeling extra confident?',
    type: 'boolean',
    options: ['Not really', 'Yes!'],
    tracksMetric: 'confidence',
    companionVariants: {
      fox: 'Luna senses your power rising 🦊',
      bunny: 'Pip is CONFIDENT BUNNY! Are you too?! 🐰',
      butterfly: 'Mira watches you stand taller ✨',
      cat: 'Nyx respects confidence. Pick yours 😼',
      owl: 'Sage notes: pre-ovulation confidence peaks — log it 🦉',
      blossom: 'Feeling extra confident? 🩷',
    },
  },
  {
    id: 'q_follicular_d8-11_2',
    phase: 'follicular',
    mode: 'adult',
    text: 'How is your sleep quality?',
    type: 'scale',
    options: ['Restless', 'Poor', 'Okay', 'Good', 'Deep'],
    tracksMetric: 'sleep',
    companionVariants: {
      fox: 'Luna asks: how was the rest? 🦊',
      bunny: 'Pip wants the sleep score! 🐰💤',
      butterfly: 'Mira asks: did dreams visit you well? ✨',
      cat: 'Nyx slept beautifully. You? 😼',
      owl: 'Sage logs sleep quality 🦉',
      blossom: 'How was your sleep? 🩷',
    },
  },
  {
    id: 'q_follicular_d8-11_3',
    phase: 'follicular',
    mode: 'adult',
    text: 'Mood right now?',
    type: 'emoji',
    options: ['😢', '😕', '😐', '🙂', '😊'],
    tracksMetric: 'mood',
    companionVariants: {
      fox: 'Luna takes your mood pulse 🦊',
      bunny: 'Pip wants the FEELS! 🐰',
      butterfly: 'Mira asks: which feeling is yours? ✨',
      cat: 'Nyx categorizes feelings. Pick one 😼',
      owl: 'Sage logs mood 🦉',
      blossom: 'How are you feeling right now? 🩷',
    },
  },
  {
    id: 'q_follicular_d8-11_4',
    phase: 'follicular',
    mode: 'adult',
    text: 'How sharp does your mind feel?',
    type: 'scale',
    options: ['Foggy', 'Slow', 'Okay', 'Sharp', 'Genius'],
    tracksMetric: 'focus',
    companionVariants: {
      fox: 'Luna sees clarity sharpening today 🦊',
      bunny: 'Pip wants to know — GENIUS BRAIN?! 🐰🧠',
      butterfly: 'Mira asks: how clear is your inner sky? ✨',
      cat: 'Nyx is always genius. You? 😼',
      owl: 'Sage notes: late follicular = peak cognition 🦉',
      blossom: 'How is your mind today? 🩷',
    },
  },
  {
    id: 'q_follicular_d8-11_5',
    phase: 'follicular',
    mode: 'adult',
    text: 'How is your skin?',
    type: 'choice',
    options: ['Breakout', 'Oily', 'Normal', 'Clear', 'Glowing'],
    tracksMetric: 'skin',
    companionVariants: {
      fox: 'Luna sees the glow continues 🦊',
      bunny: 'Pip is doing the GLOW check! 🐰✨',
      butterfly: 'Mira watches your skin shine ✨',
      cat: 'Nyx grooms approvingly 😼',
      owl: 'Sage logs skin condition 🦉',
      blossom: 'How is your skin today? 🩷',
    },
  },
];

const FOLLICULAR_D12_14: PhaseQuestion[] = [
  {
    id: 'q_follicular_d12-14_1',
    phase: 'follicular',
    mode: 'adult',
    text: 'Noticing a libido shift?',
    type: 'boolean',
    options: ['Not really', 'Yes, a bit'],
    tracksMetric: 'libido',
    companionVariants: {
      fox: 'Luna acknowledges desire as natural 🦊',
      bunny: 'Pip is FLUTTERY today! You too?! 🐰',
      butterfly: 'Mira flows with what wants to be felt ✨',
      cat: 'Nyx considers desire useful 😼',
      owl: 'Sage notes: testosterone climbs pre-ovulation 🦉',
      blossom: 'Feeling a shift in libido? 🩷',
    },
  },
  {
    id: 'q_follicular_d12-14_2',
    phase: 'follicular',
    mode: 'adult',
    text: 'Energy peak — feeling it?',
    type: 'scale',
    options: ['No', 'A bit', 'Yes', 'Big time', 'Maxed'],
    tracksMetric: 'energy',
    companionVariants: {
      fox: 'Luna feels you nearing your peak 🦊',
      bunny: 'Pip is PEAKING! Are you?! 🐰⚡',
      butterfly: 'Mira watches you bloom toward sun ✨',
      cat: 'Nyx senses peak ability 😼',
      owl: 'Sage notes: pre-ovulation = energy peak 🦉',
      blossom: 'Feeling that peak energy? 🩷',
    },
  },
  {
    id: 'q_follicular_d12-14_3',
    phase: 'follicular',
    mode: 'adult',
    text: 'Mood today?',
    type: 'emoji',
    options: ['😢', '😕', '😐', '🙂', '😊'],
    tracksMetric: 'mood',
    companionVariants: {
      fox: 'Luna asks about your inner sun 🦊',
      bunny: 'Pip wants the FEELS! 🐰☀️',
      butterfly: 'Mira asks: which mood is yours? ✨',
      cat: 'Nyx logs emotions. Pick one 😼',
      owl: 'Sage logs mood 🦉',
      blossom: 'How are you feeling? 🩷',
    },
  },
  {
    id: 'q_follicular_d12-14_4',
    phase: 'follicular',
    mode: 'adult',
    text: 'How is your appetite today?',
    type: 'choice',
    options: ['Low', 'Normal', 'High', 'Very high'],
    tracksMetric: 'appetite',
    companionVariants: {
      fox: 'Luna asks: how hungry today? 🦊',
      bunny: 'Pip wants the snack situation! 🐰',
      butterfly: 'Mira asks: what does your body want? ✨',
      cat: 'Nyx supports all appetite levels 😼',
      owl: 'Sage notes: estrogen suppresses appetite — log it 🦉',
      blossom: 'How is your appetite? 🩷',
    },
  },
  {
    id: 'q_follicular_d12-14_5',
    phase: 'follicular',
    mode: 'adult',
    text: 'Did you start something new this cycle?',
    type: 'boolean',
    options: ['Not yet', 'Yes!'],
    tracksMetric: 'motivation',
    companionVariants: {
      fox: 'Luna asks: did you plant a new seed? 🦊',
      bunny: 'Pip wants to know — NEW THING STARTED?! 🐰',
      butterfly: 'Mira watches new doors open ✨',
      cat: 'Nyx supports calculated risks 😼',
      owl: 'Sage logs new initiatives 🦉',
      blossom: 'Did you start something new? 🩷',
    },
  },
];

// ─── OVULATORY PHASE ─────────────────────────────────────────────────

const OVULATORY_D1_3: PhaseQuestion[] = [
  {
    id: 'q_ovulatory_d1-3_1',
    phase: 'ovulatory',
    mode: 'adult',
    text: 'Feeling extra social or magnetic today?',
    type: 'scale',
    options: ['Not really', 'A little', 'Yes', 'A lot', 'On fire'],
    tracksMetric: 'social_energy',
    companionVariants: {
      fox: 'Luna recognizes your peak energy 🦊',
      bunny: 'Pip is BOUNCING off the walls! You?! 🐰⚡',
      butterfly: 'Mira watches you blaze brightly ✨',
      cat: 'Nyx is impressed. Don't tell anyone 😼',
      owl: 'Sage notes: ovulation = social peak 🦉',
      blossom: 'You GLOW today! 🩷 Feel it?',
    },
  },
  {
    id: 'q_ovulatory_d1-3_2',
    phase: 'ovulatory',
    mode: 'adult',
    text: 'Mood right now?',
    type: 'emoji',
    options: ['😢', '😕', '😐', '🙂', '😊'],
    tracksMetric: 'mood',
    companionVariants: {
      fox: 'Luna takes your mood pulse 🦊',
      bunny: 'Pip wants the FEELS! 🐰',
      butterfly: 'Mira asks: which feeling is yours? ✨',
      cat: 'Nyx categorizes feelings 😼',
      owl: 'Sage logs mood 🦉',
      blossom: 'How are you feeling? 🩷',
    },
  },
  {
    id: 'q_ovulatory_d1-3_3',
    phase: 'ovulatory',
    mode: 'adult',
    text: 'Did you notice any side twinges (mittelschmerz)?',
    type: 'boolean',
    options: ['No', 'Yes'],
    tracksMetric: 'cramps',
    companionVariants: {
      fox: 'Luna observes your body announcing itself 🦊',
      bunny: 'Pip says: BODY UPDATE — twinges?! 🐰',
      butterfly: 'Mira hears the body's quiet signals ✨',
      cat: 'Nyx supports anatomical awareness 😼',
      owl: 'Sage notes: ovulation pain — log if present 🦉',
      blossom: 'Any side twinges? 🩷',
    },
  },
  {
    id: 'q_ovulatory_d1-3_4',
    phase: 'ovulatory',
    mode: 'adult',
    text: 'Libido today?',
    type: 'scale',
    options: ['Low', 'Normal', 'Elevated', 'High', 'Peak'],
    tracksMetric: 'libido',
    companionVariants: {
      fox: 'Luna acknowledges desire as natural 🦊',
      bunny: 'Pip is FLUTTERY! You too?! 🐰💗',
      butterfly: 'Mira flows with feeling ✨',
      cat: 'Nyx considers desire fine motivation 😼',
      owl: 'Sage notes: testosterone peak = libido peak 🦉',
      blossom: 'Whatever you feel is okay 🩷',
    },
  },
  {
    id: 'q_ovulatory_d1-3_5',
    phase: 'ovulatory',
    mode: 'adult',
    text: 'How focused do you feel?',
    type: 'scale',
    options: ['Foggy', 'Okay', 'Sharp', 'Laser', 'Genius'],
    tracksMetric: 'focus',
    companionVariants: {
      fox: 'Luna sees laser clarity today 🦊',
      bunny: 'Pip wants to know — BRAIN ON FIRE?! 🐰🧠',
      butterfly: 'Mira watches your mind catch the light ✨',
      cat: 'Nyx is always laser-focused. You? 😼',
      owl: 'Sage notes: peak verbal fluency window 🦉',
      blossom: 'How is your focus today? 🩷',
    },
  },
];

const OVULATORY_D4_7: PhaseQuestion[] = [
  {
    id: 'q_ovulatory_d4-7_1',
    phase: 'ovulatory',
    mode: 'adult',
    text: 'Energy level right now?',
    type: 'scale',
    options: ['Low', 'Steady', 'High', 'Very high', 'Electric'],
    tracksMetric: 'energy',
    companionVariants: {
      fox: 'Luna recognizes peak Luna energy 🦊',
      bunny: 'Pip is ELECTRIC! 🐰⚡',
      butterfly: 'Mira watches you blaze ✨',
      cat: 'Nyx is impressed (briefly) 😼',
      owl: 'Sage logs energy 🦉',
      blossom: 'How is your energy? 🩷',
    },
  },
  {
    id: 'q_ovulatory_d4-7_2',
    phase: 'ovulatory',
    mode: 'adult',
    text: 'Pain tolerance feeling higher today?',
    type: 'boolean',
    options: ['Not really', 'Yes, definitely'],
    tracksMetric: 'pain_tolerance',
    companionVariants: {
      fox: 'Luna asks: are you tougher today? 🦊',
      bunny: 'Pip wants to know — STRONG BUNNY MODE?! 🐰',
      butterfly: 'Mira sees your strength rising ✨',
      cat: 'Nyx pounces at peak ability 😼',
      owl: 'Sage notes: pain tolerance peaks at ovulation 🦉',
      blossom: 'Feeling tougher today? 🩷',
    },
  },
  {
    id: 'q_ovulatory_d4-7_3',
    phase: 'ovulatory',
    mode: 'adult',
    text: 'How are you feeling emotionally?',
    type: 'emoji',
    options: ['😢', '😕', '😐', '🙂', '😊'],
    tracksMetric: 'mood',
    companionVariants: {
      fox: 'Luna takes your emotional pulse 🦊',
      bunny: 'Pip wants the FEELS! 🐰',
      butterfly: 'Mira asks: which feeling is yours? ✨',
      cat: 'Nyx logs feelings. Pick one 😼',
      owl: 'Sage logs mood 🦉',
      blossom: 'How are you feeling? 🩷',
    },
  },
  {
    id: 'q_ovulatory_d4-7_4',
    phase: 'ovulatory',
    mode: 'adult',
    text: 'Did you exercise today?',
    type: 'boolean',
    options: ['Not yet', 'Yes!'],
    tracksMetric: 'exercise',
    companionVariants: {
      fox: 'Luna asks: did you push the edge? 🦊',
      bunny: 'Pip is HYPED to MOVE! Did you?! 🐰💪',
      butterfly: 'Mira moves like wind ✨',
      cat: 'Nyx prefers stillness 😼',
      owl: 'Sage logs exercise — peak strength window 🦉',
      blossom: 'Did you move today? 🩷',
    },
  },
  {
    id: 'q_ovulatory_d4-7_5',
    phase: 'ovulatory',
    mode: 'adult',
    text: 'Did you connect with someone meaningful today?',
    type: 'boolean',
    options: ['Not yet', 'Yes'],
    tracksMetric: 'social_energy',
    companionVariants: {
      fox: 'Luna gathers her people 🦊',
      bunny: 'Pip is SOCIAL BUNNY! Did you connect?! 🐰',
      butterfly: 'Mira lands where she's celebrated ✨',
      cat: 'Nyx accepts limited social interaction 😼',
      owl: 'Sage logs social connection 🦉',
      blossom: 'Did you connect with someone? 🩷',
    },
  },
];

const OVULATORY_D8_11: PhaseQuestion[] = [
  {
    id: 'q_ovulatory_d8-11_1',
    phase: 'ovulatory',
    mode: 'adult',
    text: 'Energy starting to settle?',
    type: 'scale',
    options: ['Still peak', 'Slightly down', 'Returning to normal', 'Calmer', 'Much calmer'],
    tracksMetric: 'energy',
    companionVariants: {
      fox: 'Luna feels the gentle turning 🦊',
      bunny: 'Pip is winding DOWN! You too?! 🐰',
      butterfly: 'Mira knows: every peak descends ✨',
      cat: 'Nyx prefers descent 😼',
      owl: 'Sage notes: post-ovulation shift begins 🦉',
      blossom: 'Energy starting to settle? 🩷',
    },
  },
  {
    id: 'q_ovulatory_d8-11_2',
    phase: 'ovulatory',
    mode: 'adult',
    text: 'Mood today?',
    type: 'emoji',
    options: ['😢', '😕', '😐', '🙂', '😊'],
    tracksMetric: 'mood',
    companionVariants: {
      fox: 'Luna takes your mood pulse 🦊',
      bunny: 'Pip wants the FEELS! 🐰',
      butterfly: 'Mira asks: which mood today? ✨',
      cat: 'Nyx logs feelings 😼',
      owl: 'Sage logs mood 🦉',
      blossom: 'How are you feeling? 🩷',
    },
  },
  {
    id: 'q_ovulatory_d8-11_3',
    phase: 'ovulatory',
    mode: 'adult',
    text: 'Did you capture any insights this week?',
    type: 'boolean',
    options: ['Not yet', 'Yes'],
    tracksMetric: 'reflection',
    companionVariants: {
      fox: 'Luna captures clarity when it visits 🦊',
      bunny: 'Pip wants to remember the FEELS! 🐰',
      butterfly: 'Mira gathers seeds of insight ✨',
      cat: 'Nyx remembers everything 😼',
      owl: 'Sage notes: capture peak-clarity insights 🦉',
      blossom: 'Did you save any insights? 🩷',
    },
  },
  {
    id: 'q_ovulatory_d8-11_4',
    phase: 'ovulatory',
    mode: 'adult',
    text: 'Sleep last night?',
    type: 'scale',
    options: ['Restless', 'Poor', 'Okay', 'Good', 'Deep'],
    tracksMetric: 'sleep',
    companionVariants: {
      fox: 'Luna asks: was rest kind to you? 🦊',
      bunny: 'Pip wants the SLEEP report! 🐰💤',
      butterfly: 'Mira asks: did the night hold you? ✨',
      cat: 'Nyx slept fabulously 😼',
      owl: 'Sage logs sleep 🦉',
      blossom: 'How was sleep? 🩷',
    },
  },
  {
    id: 'q_ovulatory_d8-11_5',
    phase: 'ovulatory',
    mode: 'adult',
    text: 'Notice changes in cervical mucus?',
    type: 'boolean',
    options: ['Not paying attention', 'Yes, drying up'],
    tracksMetric: 'cervical_mucus',
    companionVariants: {
      fox: 'Luna respects the small details 🦊',
      bunny: 'Pip is SCIENCE BUNNY! Body literacy! 🐰',
      butterfly: 'Mira reads the body like poetry ✨',
      cat: 'Nyx leaves biology to biologists 😼',
      owl: 'Sage notes: post-ovulation = drier mucus 🦉',
      blossom: 'Body literacy is power 🩷',
    },
  },
];

const OVULATORY_D12_14: PhaseQuestion[] = [
  {
    id: 'q_ovulatory_d12-14_1',
    phase: 'ovulatory',
    mode: 'adult',
    text: 'Feeling the transition to luteal?',
    type: 'boolean',
    options: ['Still feel ovulatory', 'Yes, shifting'],
    tracksMetric: 'phase_awareness',
    companionVariants: {
      fox: 'Luna watches the cycle handoff 🦊',
      bunny: 'Pip is LUTEAL BOUND! You too?! 🐰',
      butterfly: 'Mira moves with seasons ✨',
      cat: 'Nyx is READY for slower phase 😼',
      owl: 'Sage notes: corpus luteum forms 🦉',
      blossom: 'Feel the shift coming? 🩷',
    },
  },
  {
    id: 'q_ovulatory_d12-14_2',
    phase: 'ovulatory',
    mode: 'adult',
    text: 'Did you take your basal body temp today?',
    type: 'boolean',
    options: ['Not tracking BBT', 'Yes'],
    tracksMetric: 'bbt',
    companionVariants: {
      fox: 'Luna respects data 🦊',
      bunny: 'Pip is fascinated by tiny temp shifts! 🐰',
      butterfly: 'Mira knows small numbers carry meaning ✨',
      cat: 'Nyx is permanently 38.5°C 😼',
      owl: 'Sage notes: BBT rise confirms ovulation 🦉',
      blossom: 'Tracking BBT is powerful 🩷',
    },
  },
  {
    id: 'q_ovulatory_d12-14_3',
    phase: 'ovulatory',
    mode: 'adult',
    text: 'Energy today?',
    type: 'scale',
    options: ['Drained', 'Low', 'Okay', 'Good', 'High'],
    tracksMetric: 'energy',
    companionVariants: {
      fox: 'Luna asks about your fading peak 🦊',
      bunny: 'Pip wants the energy update! 🐰',
      butterfly: 'Mira asks: where is your spark? ✨',
      cat: 'Nyx requires regular reports 😼',
      owl: 'Sage logs energy 🦉',
      blossom: 'How is your energy? 🩷',
    },
  },
  {
    id: 'q_ovulatory_d12-14_4',
    phase: 'ovulatory',
    mode: 'adult',
    text: 'Did you finish something important this week?',
    type: 'boolean',
    options: ['Still pending', 'Yes!'],
    tracksMetric: 'productivity',
    companionVariants: {
      fox: 'Luna finishes what she started 🦊',
      bunny: 'Pip says — DID YOU WRAP IT?! 🐰',
      butterfly: 'Mira closes doors with care ✨',
      cat: 'Nyx finishes naps 😼',
      owl: 'Sage notes: leverage executive function pre-luteal 🦉',
      blossom: 'Did you finish the thing? 🩷',
    },
  },
  {
    id: 'q_ovulatory_d12-14_5',
    phase: 'ovulatory',
    mode: 'adult',
    text: 'Mood today?',
    type: 'emoji',
    options: ['😢', '😕', '😐', '🙂', '😊'],
    tracksMetric: 'mood',
    companionVariants: {
      fox: 'Luna takes your mood pulse 🦊',
      bunny: 'Pip wants the FEELS! 🐰',
      butterfly: 'Mira asks: which feeling is yours? ✨',
      cat: 'Nyx logs feelings 😼',
      owl: 'Sage logs mood 🦉',
      blossom: 'How are you feeling? 🩷',
    },
  },
];

// ─── LUTEAL PHASE ────────────────────────────────────────────────────

const LUTEAL_D1_3: PhaseQuestion[] = [
  {
    id: 'q_luteal_d1-3_1',
    phase: 'luteal',
    mode: 'adult',
    text: 'How was your sleep last night?',
    type: 'scale',
    options: ['Restless', 'Poor', 'Okay', 'Good', 'Deep'],
    tracksMetric: 'sleep',
    companionVariants: {
      fox: 'Luna nests for better sleep 🦊',
      bunny: 'Pip is sleepy! You too?! 🐰💤',
      butterfly: 'Mira creates her sleep sanctuary ✨',
      cat: 'Nyx is asleep. Be like Nyx 😼',
      owl: 'Sage notes: progesterone affects sleep architecture 🦉',
      blossom: 'How did you sleep? 🩷',
    },
  },
  {
    id: 'q_luteal_d1-3_2',
    phase: 'luteal',
    mode: 'adult',
    text: 'Any cravings showing up?',
    type: 'choice',
    options: ['None', 'Sweet', 'Salty', 'Carbs', 'Chocolate'],
    tracksMetric: 'cravings',
    companionVariants: {
      fox: 'Luna asks what your body needs 🦊',
      bunny: 'Pip is SNACK BUNNY! Cravings?! 🐰🍫',
      butterfly: 'Mira honors her cravings ✨',
      cat: 'Nyx supports all cravings 😼',
      owl: 'Sage notes: cravings = real biochemistry 🦉',
      blossom: 'Any cravings? 🩷 Listen to them',
    },
  },
  {
    id: 'q_luteal_d1-3_3',
    phase: 'luteal',
    mode: 'adult',
    text: 'How are you feeling emotionally?',
    type: 'emoji',
    options: ['😢', '😕', '😐', '🙂', '😊'],
    tracksMetric: 'mood',
    companionVariants: {
      fox: 'Luna takes your emotional pulse 🦊',
      bunny: 'Pip wants the FEELS! 🐰',
      butterfly: 'Mira asks: which feeling is yours? ✨',
      cat: 'Nyx logs emotions ruthlessly 😼',
      owl: 'Sage logs mood 🦉',
      blossom: 'How are you feeling? 🩷',
    },
  },
  {
    id: 'q_luteal_d1-3_4',
    phase: 'luteal',
    mode: 'adult',
    text: 'Energy level today?',
    type: 'scale',
    options: ['Drained', 'Low', 'Okay', 'Good', 'High'],
    tracksMetric: 'energy',
    companionVariants: {
      fox: 'Luna welcomes the slower season 🦊',
      bunny: 'Pip is being a CALM bunny today! 🐰',
      butterfly: 'Mira rests like the moon ✨',
      cat: 'Nyx finally feels understood 😼',
      owl: 'Sage notes: progesterone = natural calm 🦉',
      blossom: 'How is your energy? 🩷',
    },
  },
  {
    id: 'q_luteal_d1-3_5',
    phase: 'luteal',
    mode: 'adult',
    text: 'Any bloating today?',
    type: 'scale',
    options: ['None', 'Mild', 'Moderate', 'Strong', 'Severe'],
    tracksMetric: 'bloating',
    companionVariants: {
      fox: 'Luna observes bodily changes 🦊',
      bunny: 'Pip is doing the BLOAT check! 🐰',
      butterfly: 'Mira sees the body's quiet changes ✨',
      cat: 'Nyx tolerates bodily fluctuations 😼',
      owl: 'Sage notes: progesterone causes water retention 🦉',
      blossom: 'Any bloating today? 🩷',
    },
  },
];

const LUTEAL_D4_7: PhaseQuestion[] = [
  {
    id: 'q_luteal_d4-7_1',
    phase: 'luteal',
    mode: 'adult',
    text: 'How sensitive does your mood feel?',
    type: 'scale',
    options: ['Stable', 'Slightly off', 'Sensitive', 'Very tender', 'Volatile'],
    tracksMetric: 'mood',
    companionVariants: {
      fox: 'Luna is gentler in this phase 🦊',
      bunny: 'Pip is being EXTRA kind to you 🐰💛',
      butterfly: 'Mira softens like petals at dusk ✨',
      cat: 'Nyx allows extra leniency today 😼',
      owl: 'Sage notes: allopregnanolone affects mood 🦉',
      blossom: 'Mood feeling tender? 🩷',
    },
  },
  {
    id: 'q_luteal_d4-7_2',
    phase: 'luteal',
    mode: 'adult',
    text: 'Energy holding up?',
    type: 'scale',
    options: ['Drained', 'Low', 'Okay', 'Good', 'High'],
    tracksMetric: 'energy',
    companionVariants: {
      fox: 'Luna moves slower and that's wise 🦊',
      bunny: 'Pip is being CALM bunny! 🐰',
      butterfly: 'Mira knows stillness IS movement ✨',
      cat: 'Nyx is in her element 😼',
      owl: 'Sage logs energy 🦉',
      blossom: 'How is your energy? 🩷',
    },
  },
  {
    id: 'q_luteal_d4-7_3',
    phase: 'luteal',
    mode: 'adult',
    text: 'Did you journal or reflect today?',
    type: 'boolean',
    options: ['Not yet', 'Yes'],
    tracksMetric: 'reflection',
    companionVariants: {
      fox: 'Luna reflects before she acts 🦊',
      bunny: 'Pip is JOURNAL BUNNY today! 🐰📔',
      butterfly: 'Mira holds her thoughts like candles ✨',
      cat: 'Nyx supports tactical journaling 😼',
      owl: 'Sage notes: luteal = ideal reflection phase 🦉',
      blossom: 'Did you journal at all? 🩷',
    },
  },
  {
    id: 'q_luteal_d4-7_4',
    phase: 'luteal',
    mode: 'adult',
    text: 'Sleep quality?',
    type: 'scale',
    options: ['Restless', 'Poor', 'Okay', 'Good', 'Deep'],
    tracksMetric: 'sleep',
    companionVariants: {
      fox: 'Luna asks: was rest kind to you? 🦊',
      bunny: 'Pip wants the SLEEP score! 🐰💤',
      butterfly: 'Mira asks: did the night hold you? ✨',
      cat: 'Nyx slept fabulously 😼',
      owl: 'Sage logs sleep quality 🦉',
      blossom: 'How was sleep? 🩷',
    },
  },
  {
    id: 'q_luteal_d4-7_5',
    phase: 'luteal',
    mode: 'adult',
    text: 'Cravings today?',
    type: 'choice',
    options: ['None', 'Sweet', 'Salty', 'Carbs', 'Chocolate'],
    tracksMetric: 'cravings',
    companionVariants: {
      fox: 'Luna asks what calls to your body 🦊',
      bunny: 'Pip says CHOCOLATE COUNTS! 🐰🍫',
      butterfly: 'Mira honors her cravings ✨',
      cat: 'Nyx supports all cravings 😼',
      owl: 'Sage logs cravings 🦉',
      blossom: 'Any cravings today? 🩷',
    },
  },
];

const LUTEAL_D8_11: PhaseQuestion[] = [
  {
    id: 'q_luteal_d8-11_1',
    phase: 'luteal',
    mode: 'adult',
    text: 'Are PMS symptoms showing up?',
    type: 'scale',
    options: ['No', 'Mild', 'Moderate', 'Strong', 'Severe'],
    tracksMetric: 'pms',
    companionVariants: {
      fox: 'Luna grants maximum gentleness 🦊',
      bunny: 'Pip says PMS is REAL — you're BRAVE! 🐰💛',
      butterfly: 'Mira softens before the storm ✨',
      cat: 'Nyx supports comfort food as medicine 😼',
      owl: 'Sage notes: estrogen + progesterone dropping 🦉',
      blossom: 'Are PMS symptoms here? 🩷',
    },
  },
  {
    id: 'q_luteal_d8-11_2',
    phase: 'luteal',
    mode: 'adult',
    text: 'How is your mood today?',
    type: 'emoji',
    options: ['😢', '😕', '😐', '🙂', '😊'],
    tracksMetric: 'mood',
    companionVariants: {
      fox: 'Luna takes your mood pulse 🦊',
      bunny: 'Pip wants the FEELS! 🐰',
      butterfly: 'Mira asks: which feeling is yours? ✨',
      cat: 'Nyx logs emotions 😼',
      owl: 'Sage logs mood 🦉',
      blossom: 'How are you feeling? 🩷',
    },
  },
  {
    id: 'q_luteal_d8-11_3',
    phase: 'luteal',
    mode: 'adult',
    text: 'Skin breaking out?',
    type: 'choice',
    options: ['Clear', 'A bit oily', 'Breakout brewing', 'Active breakout'],
    tracksMetric: 'skin',
    companionVariants: {
      fox: 'Luna prepares her skincare 🦊',
      bunny: 'Pip is doing the SKIN check! 🐰',
      butterfly: 'Mira tends her face like a garden ✨',
      cat: 'Nyx grooms aggressively 😼',
      owl: 'Sage notes: progesterone increases sebum 🦉',
      blossom: 'How is your skin? 🩷',
    },
  },
  {
    id: 'q_luteal_d8-11_4',
    phase: 'luteal',
    mode: 'adult',
    text: 'Did you eat enough today?',
    type: 'boolean',
    options: ['Not really', 'Yes'],
    tracksMetric: 'appetite',
    companionVariants: {
      fox: 'Luna eats more when her body asks 🦊',
      bunny: 'Pip wants you FED! 🐰🍎',
      butterfly: 'Mira nourishes herself like she's worth it ✨',
      cat: 'Nyx supports increased food intake 😼',
      owl: 'Sage notes: BMR rises in luteal 🦉',
      blossom: 'Did you eat enough? 🩷',
    },
  },
  {
    id: 'q_luteal_d8-11_5',
    phase: 'luteal',
    mode: 'adult',
    text: 'Energy level today?',
    type: 'scale',
    options: ['Exhausted', 'Low', 'Okay', 'Decent', 'Good'],
    tracksMetric: 'energy',
    companionVariants: {
      fox: 'Luna asks gently about your energy 🦊',
      bunny: 'Pip wants the energy update! 🐰',
      butterfly: 'Mira asks: where is your spark? ✨',
      cat: 'Nyx requires reports 😼',
      owl: 'Sage logs energy 🦉',
      blossom: 'How is your energy? 🩷',
    },
  },
];

const LUTEAL_D12_14: PhaseQuestion[] = [
  {
    id: 'q_luteal_d12-14_1',
    phase: 'luteal',
    mode: 'adult',
    text: 'Does it feel like your period is coming?',
    type: 'boolean',
    options: ['Not yet', 'Yes, soon'],
    tracksMetric: 'period_prediction',
    companionVariants: {
      fox: 'Luna prepares her nest 🦊',
      bunny: 'Pip is the PREP BUNNY! Period coming?! 🐰',
      butterfly: 'Mira readies her cocoon ✨',
      cat: 'Nyx supports stockpiling 😼',
      owl: 'Sage notes: late luteal signals 🦉',
      blossom: 'Period feel close? 🩷',
    },
  },
  {
    id: 'q_luteal_d12-14_2',
    phase: 'luteal',
    mode: 'adult',
    text: 'How intense is the PMS?',
    type: 'scale',
    options: ['None', 'Mild', 'Moderate', 'Strong', 'Severe'],
    tracksMetric: 'pms',
    companionVariants: {
      fox: 'Luna believes severe ≠ normal 🦊',
      bunny: 'Pip says ASK FOR HELP if it's bad! 🐰',
      butterfly: 'Mira honors what your body says ✨',
      cat: 'Nyx does NOT tolerate suffering 😼',
      owl: 'Sage notes: PMDD if severe + consistent 🦉',
      blossom: 'How bad is the PMS? 🩷',
    },
  },
  {
    id: 'q_luteal_d12-14_3',
    phase: 'luteal',
    mode: 'adult',
    text: 'Mood today?',
    type: 'emoji',
    options: ['😢', '😕', '😐', '🙂', '😊'],
    tracksMetric: 'mood',
    companionVariants: {
      fox: 'Luna trusts the chart over the catastrophe 🦊',
      bunny: 'Pip says CHECK THE DAY! 🐰',
      butterfly: 'Mira asks the body before the mind ✨',
      cat: 'Nyx blames hormones routinely 😼',
      owl: 'Sage logs mood — pre-bleed dip is real 🦉',
      blossom: 'How are you feeling? 🩷',
    },
  },
  {
    id: 'q_luteal_d12-14_4',
    phase: 'luteal',
    mode: 'adult',
    text: 'Are you stocked up for your period?',
    type: 'boolean',
    options: ['Need to grab supplies', 'Yes, ready'],
    tracksMetric: 'period_prep',
    companionVariants: {
      fox: 'Luna prepares her nest 🦊',
      bunny: 'Pip is PREP BUNNY! Stocked?! 🐰',
      butterfly: 'Mira readies her cocoon ✨',
      cat: 'Nyx supports stockpiling 😼',
      owl: 'Sage logs period prep status 🦉',
      blossom: 'Got your supplies ready? 🩷',
    },
  },
  {
    id: 'q_luteal_d12-14_5',
    phase: 'luteal',
    mode: 'adult',
    text: 'Headache today?',
    type: 'boolean',
    options: ['No', 'Yes'],
    tracksMetric: 'headache',
    companionVariants: {
      fox: 'Luna asks about your head 🦊',
      bunny: 'Pip wants to know — HEADACHE?! 🐰',
      butterfly: 'Mira asks: where does pain live today? ✨',
      cat: 'Nyx demands a head check 😼',
      owl: 'Sage notes: pre-menstrual migraines common 🦉',
      blossom: 'Got a headache? 🩷',
    },
  },
];

// ─── EXPORT THE FULL BANK ────────────────────────────────────────────

/**
 * The complete seed question bank — 80 questions across all 4 phases
 * × 4 day-bands × 5 questions each. Wired into the ContentResolver via
 * SeededCohortProvider in the app's bootstrap.
 *
 * Adding cohort variants: append entries with different mode/cluster
 * combinations. The graceful-degradation chain in QuestionEngine will
 * automatically use them when matching cohorts visit the app.
 */
export const SEED_QUESTIONS: PhaseQuestion[] = [
  ...MENSTRUAL_D1_3,
  ...MENSTRUAL_D4_7,
  ...MENSTRUAL_D8_11,
  ...MENSTRUAL_D12_14,
  ...FOLLICULAR_D1_3,
  ...FOLLICULAR_D4_7,
  ...FOLLICULAR_D8_11,
  ...FOLLICULAR_D12_14,
  ...OVULATORY_D1_3,
  ...OVULATORY_D4_7,
  ...OVULATORY_D8_11,
  ...OVULATORY_D12_14,
  ...LUTEAL_D1_3,
  ...LUTEAL_D4_7,
  ...LUTEAL_D8_11,
  ...LUTEAL_D12_14,
];

/**
 * Group questions by their cohort state key, ready for the
 * SeededCohortProvider to register with ContentResolver.
 *
 * Key format matches buildStateKeyFromInputs():
 *   `${phase}_${dayBand}_${mode}_${cluster}`
 *   e.g., 'menstrual_1-3_adult_none'
 */
export function groupQuestionsByCohort(
  questions: PhaseQuestion[] = SEED_QUESTIONS
): Map<string, PhaseQuestion[]> {
  const map = new Map<string, PhaseQuestion[]>();

  for (const q of questions) {
    // Extract dayBand from the question ID (format: q_{phase}_d{dayBand}_{seq})
    const idMatch = q.id.match(/^q_[^_]+_d([0-9-]+)_/);
    const dayBand = idMatch?.[1] ?? '4-7';
    const cluster = 'none'; // All seed questions target the baseline cluster

    const key = `${q.phase}_${dayBand}_${q.mode}_${cluster}`;
    const existing = map.get(key) ?? [];
    existing.push(q);
    map.set(key, existing);
  }

  return map;
}